config/routes.rb
Rails.application.routes.draw do
  resources :bicycles do
  resources :payments, only: [:index , :new,  :create , :update]
  end
  resources :users 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/login", to: "sessions#login", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/auth/:provider/callback", to: "sessions#omniauth"

  scope '/checkout' do
    get 'success', to: 'checkout#success', as: 'checkout_success'
    post 'card', to: 'checkout#card', as: 'checkout_card'
  end


  





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  has_many :payments
  has_many :users, through: :payments
  scope :search, -> (brand){where("brand Like ?", "%#{brand}%")}
  scope :filter_by_params, ->(params){
    search(params[:search])
  }

    def self.newimages
        request_url = URI.encode("https://api.serpwow.com/live/search?api_key=1D555A9CA81341689EAD2D2E86FD3C52&q=bikes&search_type=images&_ga=2.216904086.1230371667.1626236287-562261475.1626236287&_gac=1.125980415.1626236287.CjwKCAjw87SHBhBiEiwAukSeUYYv_bAmxlv6APX0jK_1WzzUmA2LVybZjhyK8AXEZHjOMP-75XvmAhoCGj0QAvD_BwE")
        response = `curl "#{request_url}"`
        json = JSON.parse(response)
        data = json["image_results"]
        data.each do |d|
         bicycle = Bicycle.create()
         bicycle.urlpicture = d["image"]
         bicycle.brand = d["brand"]
         bicycle.save
        end 
      end

   end


    

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :bicycle

  validates :card_information, length: { in: 19..19 }
  validates :exp_date, length: { in: 4..4 }
  validates :security_code, length: { in: 3..3}


end

app/models/user.rb
class User < ApplicationRecord
    has_many :payments
    has_many :bicycles, through: :payments
    has_secure_password
    validates :username , :email, uniqueness: true
    validates :username, :email, presence: true  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        if session[:user_id]
          user = User.find(session[:user_id])
        end
    end

    def logged_in?
        !!current_user
    end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
    before_action :set_bicycle, only: [:show, :edit, :update]
    
    
    def index
        @params = params.permit(:search).to_h
        @bicycles = Bicycle.filter_by_params(@params)
    end
    
    def show
        @payment = Payment.find_or_initialize_by(user: current_user, bicycle: @bicycle)
    end

    def new
        @bicycle = Bicycle.new
    end

    def create
        @bicycle = Bicycle.create(bicycle_params)
        if @bicycle.save
        redirect_to @bicycle
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @bicycle.update(bicycle_params)
            redirect_to @bicycle
        else
            render :edit
        end
    end

      private

    def set_bicycle
        @bicycle = Bicycle.find(params[:id])
    end

    def bicycle_params
        params.require(:bicycle).permit(:brand, :wheel_size, :color, :price, :urlpicture)
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    
    def card
        @bicycle = Bicycle.find(params[:id])
        @payment = Payment.find_or_initialize_by(user: current_user, bicycle: @bicycle)
        
    end

    def success 
    end
    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    before_action :set_bicycle
    before_action :set_payment , only:[:update]
    

    def index
        @bicycle = Bicycle.find(params[:bicycle_id])
        @payments = @bicycle.payments
        
    end

    def new
        @bicycle = Bicycle.find(params[:bicycle_id])
        @payment = Payment.find_or_initialize_by(user: current_user, bicycle: @bicycle)
        
    end

    

    def create
        @payment = @bicycle.payments.build(payment_params)
        @payment.user = current_user
        if @payment.save
            redirect_to checkout_success_path
        else
            render :new
        end
    end

    

    def update
        if @payment.update(payment_params)
            redirect_to checkout_success_path
        else
            redirect_to @bicycle
        end
    end

    private

    def set_payment
        @payment = Payment.find(params[:id])
    end

    def set_bicycle
        @bicycle = Bicycle.find(params[:bicycle_id]) if params[:bicycle_id]
    end

    def payment_params
        params.require(:payment).permit(:card_information, :exp_date, :security_code)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login  
          
    end

    def create
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user
        else
            flash[:errors] = ["Invalid Username or Password!"]
            redirect_to login_path
        end
    end

    def logout
        session.clear
        redirect_to new_user_path
    end

    def omniauth
        user = User.find_or_create_by(uid: auth[:uid] , provider: auth[:provider]) do |u|
            u.username = request.env['omniauth.auth'][:info][:first_name]
            u.email = request.env['omniauth.auth'][:info][:email]
            u.password = SecureRandom.hex(15)
        end
            if user.valid?
                session[:user_id] = user.id
                redirect_to user
            else
                redirect_to login_path
            end

        
    end

    private

    def auth
    request.env['omniauth.auth']

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to login_path
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username , :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper

    
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bicycles/_form.html.erb
<%= form_for @bicycle do |u| %>
    <%= u.label :brand %>
    <%= u.text_field :brand %><br>
    <%= u.label :wheel_size %>
    <%= u.text_field :wheel_size %><br>
    <%= u.label :color %>
    <%= u.text_field :color %><br>
    <%= u.label :price %>
    <%= u.number_field :price%><br>
    <%= u.label :urlpicture %>
    <%= u.url_field :urlpicture %><br>
    <%= u.submit "Submit!"%><br>
    <% end %>

app/views/bicycles/edit.html.erb
<h1>Edit your Bicycles</h1>
<%= render "form" %>

app/views/bicycles/index.html.erb
<h1>List Of Bicycles</h1>
<div id="products">
<%= form_tag bicycles_path , method: :get do%>
    <%= label_tag :brand%>
    <%= text_field_tag :search %></br>
    <%= submit_tag "Search!"%>
    <% end %>
   
    
<% @bicycles.each do |b| %>
    <div class="product">
    <p><%= link_to b.brand , b %></p>
    <img src=<%= b.urlpicture %>>
    <p>Price : <%= b.price  %>$</p>
    </div>
     <% end %>

</div>

app/views/bicycles/new.html.erb
<h1>Sell your Bicycles</h1>
<%= render "form" %>
    

app/views/bicycles/show.html.erb
<h1><img src=<%= @bicycle.urlpicture %>></h1>
<h1>Brand: <%= @bicycle.brand %></h1>
<h1>Wheel Size: <%= @bicycle.wheel_size %></h1>
<h1>Color: <%= @bicycle.color %></h1>
<h1>Price: $<%= @bicycle.price %></h1>
</br>
<h1>Payment</h1>
    <p><%= button_to "Card ", checkout_card_path , method: :post , params: {id: @bicycle.id}%></p>

</br>
</br>
</br>

app/views/checkout/card.html.erb
<div class="col-25">
    <div class="container">
      <h4>Your Cart </h4>
        <p>Brand: <%= @bicycle.brand %></p>
        <p><img src=<%= @bicycle.urlpicture %>></p>
        <p>Price: $<%= @bicycle.price %></p>
      <hr>
        </div>
  </div>
</div>
<%= form_for [@bicycle , @payment] do |p| %>
  <%= render partial: "layouts/errors", locals: {record: @payment} %>

<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          
          <div class="col-50">
          
            <h3>Payment</h3>
           
            
            <%= p.label :card_number %>
            <%= p.text_field :card_information %><br>
            <div class="row">
              <div class="col-50">
              <%= p.label :exp_year %>
              <%= p.text_field :exp_date %><br>
              </div>
              <div class="col-50">
              <%= p.label :security_code %>
              <%= p.text_field :security_code %><br>
              </div>
            </div>
          </div>

        </div>
        
        <%= p.submit "Submit Payment"%><br>
      </form>
    </div>
  </div>
  <% end %>

  

app/views/checkout/success.html.erb
<h1>Your Payment is Successful</h1>

<% if current_user.id == Payment.last.user.id %>
    <div class="product">
    <p>Brand: <%= Payment.last.bicycle.brand  %></p>
    <img src=<%= Payment.last.bicycle.urlpicture  %>>
    <p>Price : <%= Payment.last.bicycle.price %>$</p>
    </div>

    
<% end %>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
    <ul class= "errors">
   <% record.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end%>
        </ul>
        <% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type , msgs|%>
   <ul class="flash <%= type %>">
    <%= msgs.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

app/views/layouts/_nav.html.erb
<nav id="mainMenu">
<% if logged_in? %>
<div id="menu"><%= link_to "Inventory" , bicycles_path%>
<%= link_to "Sell Your Bicycle" , new_bicycle_path%>

<span class="userinfo"> Hello <%= current_user.username %> 
<%= link_to "Logout" , logout_path, method: "delete" %></span>
</div>
<% else %>
<div id="login">
<%= link_to "Login" , login_path %>
<%= link_to "Sign Up" , new_user_path %>
</div>
<% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicycle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "layouts/nav" %>
   <%= render "layouts/flash" %> 
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h1>Your Transaction History</h1>
 <% @payments.each do |p| %>
    
    <% if p.user.id == current_user.id %>
    <img src=<%= p.bicycle.urlpicture  %>>
    <p>Credit Card Number: <%= p.card_information %></p>
    <p>Experation Date:<%= p.exp_date %></p>
    <p>Security Code:<%= p.security_code %></p>
    <p>Bicycle Brand:<%= p.bicycle.brand %></p>
    <p>Buyer Name:<%= p.user.username %></p>
    <% else %>
    <% end %>
<% end %>

<%= link_to "New Payment" , new_bicycle_payment_path(@bicycle)%>

app/views/payments/new.html.erb
<h1>Hello</h1>
<%= form_for [@bicycle , @payment] do |p|  %>

  <div class="row">
    <div class="col-75">
      <div class="container">
        <form action="/action_page.php">
  
          <div class="row">
            
            <div class="col-50">
              <h3>Payment</h3>
             
              
              <%= p.label :card_number %>
              <%= p.text_field :card_information %><br>
              <div class="row">
                <div class="col-50">
                <%= p.label :exp_year %>
                <%= p.text_field :exp_date %><br>
                </div>
                <div class="col-50">
                <%= p.label :security_code %>
                <%= p.text_field :security_code %><br>
                </div>
              </div>
            </div>
  
          </div>
          <%= p.label :bicycle%>
          <%= p.collection_select :bicycle_id, Bicycle.all, :id, :brand, prompt: true %>
          <%= p.submit "Submit Payment"%><br>
        </form>
      </div>
    </div>
    <% end %>
  

app/views/users/new.html.erb
<h1>Welcome Matt Bicycle Shop</h1>
<%= form_for @user do |u| %>
<%= render partial: "layouts/errors", locals: {record: @user} %>
<%= u.label :username %>
<%= u.text_field :username%><br>
<%= u.label :email %>
<%= u.text_field :email%><br>
<%= u.label :password %>
<%= u.password_field :password%><br>
<%= u.label :password_confirmation %>
<%= u.password_field :password_confirmation%><br>
<%= u.submit "Sign Up!"%><br>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
Email: <%= @user.email %>